### PR TITLE
fix(postinstall): avoid potential infinite loop

### LINKED ISSUE #17196: appium-chromedriver: postinstall should not attempt to install chromedriver infinity times
When running the postinstall lifecycle script `npm-install.js`, there's a call to `waitForDeps()`.  If the callback fails _prior_ to the `doInstall()` call, it will continue in an infinite loop, because:

```js
  waitForDeps(function wait (err) {
    if (err) {
      // this should only happen on local install (i.e., npm install in this directory)
      log.warn(`Unable to import install script: ${err.message}`);
      log.warn(`Re-run 'npm run chromedriver' manually.`);
      return;
    }
    require(BUILD_PATH).doInstall().catch(function installError (err) {
      // ...
    });
  }
```

If `err` is truthy, then the callback will exit continually be called again.  Either that `return` should be a `process.exit(1)`, or there should be a timeout.

I'm unsure who "owns" `appium-chromedriver`--I can address this myself if needed--but just wanted to create a tracking issue anyway.

This was causing infinite execution time in Appium's E2E tests due to a misconfiguration.

### PR DESCRIPTION
**Pull request by boneskull**
Resolves appium/appium#17196

If the postinstall script (`install-npm.js`) is unable to load the install script, the script will now fail instead of infinitely retrying to load the module.

### CODE REVIEW

**Comment by boneskull** [comment]
ugh, I can't test this very well due to internet problems

**Comment by boneskull** [comment]
This code is weird and seems like it exists because the `prepare` script isn't being run. Why isn't `prepare` being run?

**Comment by jlipps** [comment]
what's the way to best test this? i can try it

**Comment by boneskull** [comment]
@jlipps Because `prepare` runs _after_ `postinstall`.  Anyway, I think I got it working.

**Comment by mykola-mokhnach** [comment]
hm is something wrong on Windows?

File: install-npm.js [hunk 1]
```diff
@@ -1,82 +1,56 @@
...
 
-const BUILD_RETRIES = 200;
-const BUILD_RETRY_INTERVAL = 1000;
+const B = require('bluebird');
+
+B.config({
+  cancellation: true,
+});
+
+const {fs} = require('appium/support');
```
Comment (mykola-mokhnach) [inline install-npm.js:18]: I'm not sure if this peer dependency would always exist. Perhaps it would be safer to use native `fs.promises` methods here rather than imported from appium

File: install-npm.js [hunk 2]
```diff
@@ -1,82 +1,56 @@
...
+    log.info('Project not yet built; building...');
+    await exec('npm', ['run', 'build'], {logger: log});
   }
-  check();
-}
 
-function main () {
   // check if we should skip install
   if (!_.isEmpty(process.env.APPIUM_SKIP_CHROMEDRIVER_INSTALL) || !_.isEmpty(process.env.npm_config_chromedriver_skip_install)) {
     log.warn(`'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable set, or '--chromedriver-skip-install' flag set.`);
```
Comment (mykola-mokhnach) [inline install-npm.js:38]: `--chromedriver-skip-install` this is probably not relevant anymore

File: install-npm.js (hunk 1 above)
Comment (boneskull) [reply install-npm.js:18]: hmm, yeah.

File: install-npm.js [hunk 3]
```diff
@@ -1,82 +1,58 @@
...
-      }
-    }
+async function main () {
+  // always build if not yet built.
+  // this should only happen in a working copy / dev environment.
+  try {
+    await fs.stat(BUILD_PATH);
+  } catch {
+    log.info('Project not yet built; building...');
+    const npmCommand = os.type() === 'Windows_NT' ? 'npm.cmd' : 'npm';
```
Comment (mykola-mokhnach) [inline install-npm.js:36]: I usually use `process.platform`, but this should also be ok

**Review by mykola-mokhnach — APPROVED** [review]
